# Generated by Django 4.2.16 on 2024-10-10 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('SM', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large')], default='M', max_length=2)),
                ('price', models.IntegerField()),
                ('serial_number', models.CharField(max_length=250)),
                ('stock_size', models.IntegerField()),
                ('listed', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-listed'],
                'indexes': [models.Index(fields=['-listed'], name='product_pro_listed_d90955_idx')],
            },
        ),
    ]
